use std::error::Error;

fn main() -> anyhow::Result<()> {
    Ok(())
}
